version: '3.1'

services:
    db:
        image: docker.io/bitnami/postgresql:15
        restart: always
        ports:
            - '5432:5432'
        volumes:
            - 'postgresql_data:/bitnami/postgresql'
        environment:
            POSTGRES_PASSWORD: thepassword

volumes:
    postgresql_data:
        driver: local
